[package]
name = "engraver"
version = "0.1.0"
edition = "2021"

[dependencies]
smufl = "0.2.0"
svg = "0.13.0"
thiserror = "1.0.40"
tracing = "0.1.37"

[[bin]]
name = "svg-test"

[dev-dependencies]
rstest = { version = "0.17.0", default_features = false }
